name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  should_run_tests:
    name: Should run tests
    runs-on: ubuntu-latest
    outputs:
      shouldRunTests: ${{ env.SHOULD_RUN_TESTS }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        if: github.event_name == 'pull_request'
        with:
          filters: |
            shouldRequireApprovalFromPerson:
              - '!test.md'
      - run: echo "::set-env name=SHOULD_RUN_TESTS::$SHOULD_RUN"
        if: github.event_name == 'pull_request'
        env:
          SHOULD_RUN: ${{ steps.filter.outputs.shouldRunTests }}
      - run: echo "::set-env name=SHOULD_RUN_TESTS::true"
        if: github.event_name != 'pull_request'

  test:
    name: Test
    needs: should_run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
