name: Test

on:
  pull_request:

jobs:
  jest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            shouldRequireApprovalFromPerson:
              - '!test.md'
      - uses: ./
        with:
          approve: ${{ steps.filter.outputs.shouldRequireApprovalFromPerson == 'false' }}
